### PR TITLE
feat: add paste option

### PR DESCRIPTION
**Pull request by martiliones**
### Description

Hello, I just tried this tool for markdown files and found that writing some parts might not seem natural (like links), so I decided to create an option for pasting text

Example syntax:

```js
--01----------

--02----------
// see
--03----------
// see https://github.com/antfu/retypewriter/
-----options--
paste: true
wait: 0
--------------
```

I also implemented the `wait` option as you can see.

### Additional context

It would be nice if autodetection of inserting text or finding links was implemented in the future.

btw why was the remove snap function removed from CodeLens? The commented code seems to work

### CODE REVIEW

**Comment by antfu** [comment]
> why was the remove snap function removed from CodeLens? The commented code seems to work

Because I found the actions become verbose. To remove a snap, the user could simply select and delete them, this also makes it more explicit and avoid accident clicks.

**Comment by antfu** [comment]
Great feature, thanks!

**Comment by antfu** [comment]
Emm. this seems to break the test, can you have a look? Thanks

**Comment by antfu** [comment]
Fixed in 2186aed7d475453c4c1b5ef925adf91367464ee0

**Comment by martiliones** [comment]
> Because I found the actions become verbose. To remove a snap, the user could simply select and delete them, this also makes it more explicit and avoid accident clicks.

Users also should change id for all future steps, shouldn't they?
```diff
- --01----------
- // text 1
- --02----------
+ --01----------
// text 2
- --03----------
+  --02----------
// text 3
```

**Pull request merged**
